config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[show edit update destroy]
  resource :admin, only: [:show]
  resource :allevents, only: [:show]
  resources :organizations, param: :slug do
    patch :validate # only for the admin of the website
    resources :follows, only: %i[create destroy]
    resources :events, param: :slug do
      resources :participations, only: %i[create destroy]
    end
  end
  resources :articles, param: :slug do
    resources :article_likes, only: %i[create destroy]
    resources :article_comments
  end
  root to: 'home#index'
  get '/static/:page' => 'static#show'
  get "static/team", :as => 'team'
  mount Thredded::Engine => '/forum'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/show.html.erb
<div class="container-fluid bg-light py-5">
  <br>
</div>

<div class="container">
  <div class="row mt-n5 text-center">
    <div class="col-md-12 h1">
      DASHBOARD ADMIN
    </div>
  </div>
  <div class="row border text-center py-4 mb-2">
    <div class="col-2 mb-4 text-md-left">
      Graphique sur les Utilisateurs 
    </div>
    <div class="col-10 py-2">
      <%= line_chart [{name: "Utilisateurs créés", data: User.group_by_day(:created_at).count },{name: "Utilisateurs connectés", data: User.group_by_day(:last_sign_in_at).count }] %>
    </div>
  </div>
  <div class="row border text-center py-4 pl-3 mb-2">
    Liste des associations 
      <ul class="list-group col-12 text-left py-2"> 
        <li class="row py-2"> 
          <div class="col-2 h6">ID</div>
          <div class="col-2 h6">NOM</div>
          <div class="col-2 h6">USER.ID</div>
          <div class="col-2 h6">#RNA</div>
          <div class="col-2 h6">VALIDATION</div>
        </li>
        <% @organizations.each do |organization| %>
         <li class="row py-2">
          <div class="col-2 h6"><%= organization.id %> </div>
          <div class="col-2 h6"><%= organization.name %> </div>
          <div class="col-2 h6"><%= organization.user_id %> </div>
          <div class="col-2 h6"><%= organization.num_rna %> </div>
          <div class="col-2 text-left">
            <% if organization.validatedbyadmin == true %>
              <%= link_to "OK", organization_validate_path(organization.slug), method: :patch, data: {confirm: "Etes vous sûre? Le compte sera ou non validé"},  class: 'btn btn-sm btn-success' %></div>
            <% else %>
              <%= link_to "A valider", organization_validate_path(organization.slug), method: :patch, data: {confirm: "Etes vous sûre? Le compte sera ou non validé"},  class: 'btn btn-sm btn-danger' %></div>
            <% end %>
          <div class="col-1 text-right"><%= link_to 'Supprimer', organization_path(organization.slug), method: :delete, data: {confirm: "Etes vous sûre? Le compte sera définitivement supprimé"},  class: 'btn btn-sm btn-danger' %></div>
          <div class="col-1 text-right"><%= link_to 'Editer', edit_organization_path(organization.slug),  class: 'btn btn-sm btn-primary' %></div>
        </li>

        <%end%> 
      </ul>
  </div>
  <div class="row border text-center py-4 pl-3 mb-2">
    Liste des Utilisateurs 
      <ul class="list-group col-12 text-left py-2"> 
        <li class="row py-2"> 
          <div class="col-1 h6"> ID </div>
          <div class="col-3 h6"> PSEUDO </div>
          <div class="col-3 h6"> EMAIL </div>
          <div class="col-1 h6"> #POSTS </div>
          <div class="col-1 h6"> ASSOC </div>
        </li>
        <% @users.each do |user| %>
         <li class="row py-2"> 
          <% unless user.admin == true %> 
            <div class="col-1 h6"><%= user.id %> </div>
            <div class="col-3 h6"><%= user.name %> </div>
            <div class="col-3 h6"><%= user.email %> </div>
            <div class="col-1 h6"><%= user.thredded_posts.count %> </div>
            <div class="col-1 h6"><% if user.organization.nil? %> - <%else%><%= user.organization.id %> <%end%></div>
          <%end%>
        </li>
        <%end%> 
      </ul>
      </div>
  </div>
</div>