config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[show edit update destroy]
  resource :admin, only: [:show]
  resource :allevents, only: [:show]
  resources :organizations, param: :slug do
    patch :validate # only for the admin of the website
    resources :follows, only: %i[create destroy]
    resources :events, param: :slug do
      resources :participations, only: %i[create destroy]
    end
  end
  resources :articles, param: :slug do
    resources :article_likes, only: %i[create destroy]
    resources :article_comments
  end
  root to: 'home#index'
  get '/static/:page' => 'static#show'
  get "static/team", :as => 'team'
  mount Thredded::Engine => '/forum'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  has_many :article_likes, dependent: :destroy
  has_many :article_comments, dependent: :destroy
  has_one_attached :illustration
  after_create :new_publication_send
  extend FriendlyId
  friendly_id :title, use: :slugged

  def new_publication_send
    @organization = User.find(user_id).organization
    @organization.followers.each do |follower|
      UserMailer.new_publication_email(follower, @organization, self).deliver_now
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :authenticate_author_or_admin, only: %i[edit update destroy]
  before_action :authenticate_canbeauthor_or_admin, only: %i[new create]

  def new
    @article = Article.new
  end

  def show
    @article = Article.friendly.find_by_slug(params[:slug])
    @user = User.find(@article.user_id)
    @organization = User.find(@article.user_id).organization
    @comments = @article.article_comments.order('created_at desc')
    @articles = Article.all.reject { |article| article.id == @article.id }.sample(3)
  end

  def index
    @articles = Article.all.order('created_at desc')
  end

  def create
    @article = Article.new(user_id: current_user.id, title: params[:article][:title], content: params[:article][:content], illustration: params[:article][:illustration])
    if @article.save
      flash[:success] = 'Article créé - Merci pour votre contribution!'
      redirect_to article_path(@article.slug)
    else
      flash.now[:error] = "Désolé il y a une erreur :#{@article.errors.full_messages.to_sentence}"
      render :new
    end
  end

  def edit
    @article = Article.friendly.find_by_slug(params[:slug])
    @user = User.find(@article.user_id)
  end

  def update
    @article = Article.friendly.find_by_slug(params[:slug])
    post_params = params.require(:article).permit(:title, :content, :illustration)
    if @article.update(post_params)
      flash[:success] = "L'article a bien été mis à jour"
      redirect_to article_path(@article.slug)
    else
      flash[:error] = "Désolé il y a une erreur :#{@article.errors.full_messages.to_sentence}"
      redirect_to edit_article_path(@article.slug)
    end
  end

  def destroy
    @article = Article.friendly.find_by_slug(params[:slug])
    @article.destroy
    flash[:success] = "L'article a été supprimé"
    redirect_to articles_path
  end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
  def authenticate_author_or_admin # the author of the article or admin
    @article = Article.friendly.find_by_slug(params[:slug])
    unless current_user && (current_user.id == @article.user_id || current_user.admin == true)
      redirect_to root_path
    end
  end

  def authenticate_canbeauthor_or_admin # the author of the article or admin
    unless current_user && (current_user.organization.nil? == false || current_user.admin == true)
      redirect_to root_path
    end
  end
end

app/views/articles/_article_card.html.erb
<div class="col-md-4 mt-4">
    <div class="post-module">
        <!-- Thumbnail-->
        <div class="thumbnail">
            <div class="date">
            <div class="day"><%= article.article_likes.count %></div>
            <div class="month" style="color: white"><i  class="fas fa-thumbs-up"></i></div>
            </div>
            <%if article.illustration.attached?%>
                <%= image_tag article.illustration, class:"card-img-top"%>
            <%else%>
                <%= image_tag "article.jpg", class:"card-img-top"%>
            <%end%>
        </div>
        <!-- Post Content-->
        <div class="post-content">
            <div class="category"><%= link_to article.user.organization.name, organization_path(article.user.organization.slug), {:style=>'color:#FFFFFF;'}%></div>
            <h3 class="title"><%= article.title %></h3>
            <p class="description"></p>
            <div class="post-meta d-flex justify-content-between flex-row align-items-center">
            <span class="comments"><i class="fas fa-user-circle"></i> <%= article.user.name %></span>
             <%= link_to "Lire l'article",  article_path(article.slug), :class => "btn btn-primary text-white" %>
            </div>
        </div>
    </div>
</div>

app/views/articles/_articles_form.html.erb
<div class="container my-3">
  <%= form_for @article do |f| %>
    <div class="row py-3">
      <div class="col">
        <%= label_tag "Titre de l'article : " %> <br>
        <%= f.text_field :title, class:'form-control w-50' %>
      </div>
    </div>

    <div class="row py-3">
      <div class="col">
        <%= label_tag "Contenu : " %> <br>
        <%= f.text_area :content, class:'form-control', rows: '10' %>
      </div>
    </div>

    <div class="row py-3">
      <div class="col">
        <%= label_tag "Ajoutez une photo à l'évènement"%><br/>
        <%= f.file_field :illustration %>
      </div>
    </div>

    <div class="row py-3 text-center">
      <div class="col">
        <%= f.submit "Valider l'article", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_articles_list.html.erb
<div class="container">
    <div class="card-deck">
        <% @articles.each do |article| %>
            <%= link_to (render 'articles/article_card', article: article), article_path(article.slug)%>
        <% end %>  
    </div>
</div>

app/views/articles/edit.html.erb
<div class="container-fluid py-5 bg-orange-gradient">
  <h1 class="text-center">Modifier l'article</h1>
</div>

<%= render 'articles/articles_form' %>


<div class="row py-3">
  <div class="col text-center">
    <% if current_user && (current_user == @user || current_user.admin == true)%>
      <p>Pour supprimer cet article, cliquer ici : </p>
      <%= link_to "Supprimer",article_path(@article.slug), method: :delete, data: {confirm: "Etes vous sur(e)? L'article sera définitevement supprimé"}, class: 'btn btn-outline-primary' %>
    <%end%>
  </div>
</div>

app/views/articles/index.html.erb
<h1 class="d-flex justify-content-center mt-5">Les publications de nos membres</h1>
<div class="container">
  <div class="card-deck my-3">
      <%= render 'articles/articles_list'%>
  </div>
  <div class="d-flex flex-row justify-content-center mt-5">
    <% if current_user && current_user.organization.nil? == false %>
      <%= link_to "Ajouter un nouvel article", new_article_path(), :class => " btn btn-primary text-white" %>
    <%end%>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container-fluid py-5 bg-orange-gradient">
  <h1 class="text-center">Écrire un nouvel article</h1>
</div>

<%= render 'articles/articles_form' %>

app/views/articles/show.html.erb
<!-- ***** Gradient banner ***** -->
<div class="container-fluid py-5 bg-orange-gradient">
  <br>
</div>

<div class="container mt-n5">
  <!-- ***** Title && Author ***** -->
  <div class="row">

    <div class="col-md-9 text-center text-md-left">
      <!-- Title -->
      <h1><%= @article.title %></h1>
      <!-- Author -->
      <h5 class="mb-3">Par :
        <% if current_user %> 
          <%= link_to "#{@article.user.name}", thredded.new_private_topic_path(private_topic: {title: "A propos de l'article '#{@article.title}'", user_names: "#{@article.user.name}"}) %>
        <%else%>
          <%= @article.user.name %>
        <%end%>
          , de l'association <%= link_to @organization.name, organization_path(@organization.slug)%> </h5>
    </div>
    <div class="col-md-3 text-center text-md-right">
      <% if current_user && (current_user == @user || current_user.admin == true)%>
        <%= link_to "Modifier l'article", edit_article_path(@article.slug), class: 'btn btn-sm btn-primary' %> 
        <%= link_to "Supprimer l'article", article_path(@article.slug), method: :delete, class: 'btn btn-sm btn-secondary' %>
      <%end%>
    </div>
  </div>

  <!-- ***** Article's body ***** -->
  <div class="row py-3 my-3">
    <div class="col py-3">
      <p>
        <%= @article.content %>
      </p>
    </div>
  </div>

  <!-- ***** Thank Section ***** -->
  <div class="row">
    <div class="col text-center">
      <p id="count_like">
        <%= @article.article_likes.count %> personne(s) ont aimé cet article.
      </p>
      <p>
        Vous avez trouvé cet article intéressant ? Faites le savoir à son auteur :
      </p>
        <%if current_user%>
          <div id="like">
           <%= render 'article_likes/like_button'%>
          </div>
        <%else%>
          <%= link_to "Like", new_user_session_path, :class => "ml-3 btn btn-primary"%>
        <%end%>
      </div>
  </div>
</div>

    <!-- ***** Linked Pages Section ***** -->
<div class="container-fluid bg-orange-gradient py-5 my-3">
        <h3 class="text-center pb-2">Articles similaires qui pourraient vous intéresser : </h3>
            <%= render 'articles/articles_list'%>
</div>

    <!-- ***** Comment Section ***** -->
<div class="container">
    <div class="row my-3">
      <div class="col-md-6">
        <h3 class="py-3">
          Précédents commentaires</h3>
        <%if @comments.count == 0 %>
          <p id="comments_article" class="py-3">Soyez la première personne à réagir à cet article !</p>
        <%else%>
          <div id="comments_article">
            <%= render 'article_comments/comment_list' %>
          </div>
        <%end%>
      </div>
      <div class="col">
        <h3 class="py-3">Réagir à cet article</h3>
        <%= form_tag article_article_comments_path(@article.slug), remote:true, method: "post" do %>
          <div class="form-group">
            <%= text_area_tag 'content', "", class: "form-control"%>
          </div>
          <div class="text-right">
            <%= submit_tag "Commenter", class: 'btn btn-primary' %>
          </div>
        <%end%>
    </div>
  </div>
</div>