config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[show edit update destroy]
  resource :admin, only: [:show]
  resource :allevents, only: [:show]
  resources :organizations, param: :slug do
    patch :validate # only for the admin of the website
    resources :follows, only: %i[create destroy]
    resources :events, param: :slug do
      resources :participations, only: %i[create destroy]
    end
  end
  resources :articles, param: :slug do
    resources :article_likes, only: %i[create destroy]
    resources :article_comments
  end
  root to: 'home#index'
  get '/static/:page' => 'static#show'
  get "static/team", :as => 'team'
  mount Thredded::Engine => '/forum'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :organization
  belongs_to :address
  has_one_attached :illustration
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  validates :title, presence: true
  validates :start_date, presence: true
  validate :start_in_the_future
  validate :end_after_start_date
  after_create :new_event_send
  extend FriendlyId
  friendly_id :title, use: :slugged

  def start_in_the_future
    if start_date.to_date < DateTime.now.to_date
      errors.add(:start_date, "L'évènement ne peut etre dans le passé")
    end
  end

  def end_after_start_date
    unless end_date.nil?
      if end_date.to_date < start_date.to_date
        errors.add(:end_date, "L'évènement ne peut finir avant d'avoir débuté")
      end
    end
  end

  def new_event_send
    @organization = Organization.find(organization_id)
    @organization.followers.each do |follower|
      UserMailer.new_event_email(follower, @organization, self).deliver_now
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include EventsHelper
  before_action :authenticate_user, except: %i[show index]
  before_action :authenticate_user_event_or_admin, only: %i[new create edit update]
  before_action :address_validation, only: [:create]

  def new
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
  end

  def index
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
    @events = Event.where(organization_id: @organization.id).order('created_at desc')
  end

  def show
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
    @event = Event.friendly.find_by_slug(params[:slug])
    @events = Event.where(organization_id: @organization.id).reject { |event| event.id == @event.id }.sample(3)
    @attendants = @event.participations.map { |participe| User.find(participe.user_id).name }
  end

  def create
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
    @event = Event.new(organization_id: @organization.id, address_id: @address.id, start_date: params[:start_date], end_date: params[:end_date], title: params[:title], description: params[:description], illustration: params[:illustration])
    if @event.save
      flash[:success] = 'Evenement créé !'
      redirect_to organization_event_path(@organization.slug, @event.slug)
    else
      flash.now[:error] = "Désolé il y a une erreur :#{@event.errors.full_messages.to_sentence}"
      @address.destroy
      render :new
    end
  end

  def edit
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
    @event = Event.friendly.find_by_slug(params[:slug])
    @address = Address.find(@event.address_id)
  end

  def update
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
    @event = Event.friendly.find_by_slug(params[:slug])
    @address = Address.find(@event.address_id)
    if @event.update(post_params) && @address.update(address_params)
      flash[:success] = 'Les informations ont bien été prises en compte'
      redirect_to organization_event_path(@organization.slug, @event.slug)
    else
      flash.now[:error] = "Désolé il y a une erreur :#{@event.errors.full_messages.to_sentence} #{@address.errors.full_messages.to_sentence}"
      render :edit
    end
  end

  def destroy
    @event = Event.friendly.find_by_slug(params[:slug])
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
    @event.destroy
    # @address.destroy
    flash[:success] = "L'évènement a été supprimé"
    redirect_to organization_path(@organization.slug)
  end

  private

  def post_params
    params.require(:event).permit(:start_date, :end_date, :title, :description, :illustration, address_attributes: %i[number street additionnal_information zip_code city])
  end

  def address_params
    params.require(:address).permit(:number, :street, :additionnal_information, :zip_code, :city)
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  	def authenticate_user_event_or_admin # the admin of the organiation or admin
	    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
	    unless (current_user && current_user.organization.nil? == false && current_user.organization.id == @organization.id) || (current_user && current_user.admin == true)
	      redirect_to root_path
	    end
  	end
end

app/views/events/_event_card.html.erb
<div class="col-md-4 mt-4">
    <div class="post-module">
        <!-- Thumbnail-->
        <div class="thumbnail">
            <div class="date">
            <div class="day"><%= event.start_date.strftime("%-d") %></div>
            <div class="month"><%= event.start_date.strftime("%b")%></div>
            </div>
            <%if event.illustration.attached?%>
                <%= image_tag event.illustration, class:"card-img-top"%>
            <%else%>
                <%= image_tag "event.jpg", class:"card-img-top"%>
            <%end%>
        </div>
        <!-- Post Content-->
        <div class="post-content">
            <div class="category"> <% unless event.address.city.nil? %><%= event.address.city %> <%end%></div>
            <h3 class="title"><%= event.title %></h3>
            
            <div class="post-meta d-flex justify-content-between flex-row align-items-center">
            <span class="comments"><i class="fas fa-users"></i></i><a href="#"> <%= event.participations.size%></a></span>
             <%= link_to "Voir l'évènement", organization_event_path(Organization.find(event.organization_id).slug,event.slug), :class => "btn btn-primary text-white" %>
            </div>
        </div>
    </div>
</div>

app/views/events/_events_list.html.erb
<div class="container">
  <div class="card-deck my-3">
    <% @events.each do |event| %>
      <%= link_to (render 'events/event_card', event: event), organization_event_path(event.organization.slug,event.slug) %>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container-fluid py-5 bg-orange-gradient">
  <h1 class="text-center">Modifier les informations</h1>
</div>
<div class="container d-flex justify-content-center ">
<div class="col-md-8 order-md-1">
<%= form_for [@organization, @event] do |f| %>
  <div class="mb-3">
    <%= label_tag "Titre de l'évènement*" %> <br/>
    <%= f.text_field :title, class: "form-control", placeholder: "Titre"%>
    <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire </div>
  </div>
  <div class="mb-3">
    <%= label_tag "Description de l'évènement*" %> <br/>
    <%= f.text_area :description, class: "form-control"%>
    <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire</div>
  </div>
  <div class="mb-3">
    <%= label_tag "Début de l'évènement*" %> <br/>
    <%= f.datetime_select :start_date, class: "form-control"%>
    <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire</div>
  </div>
  <div class="mb-3">
    <%= label_tag "Fin de l'évènement" %> <br/>
    <%= f.datetime_select :end_date, class: "form-control"%>
    <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire</div>
  </div>
  <div class="mb-3">
    <%= fields_for @address do |ff| %>
      <%= label_tag "Lieu de l'évènement"%>
      <div class="row mb-1">
        <div class="col">
          <%= ff.text_field :number, class: "form-control", placeholder: "N°" %>
        </div>
        <div class="col">
          <%= ff.text_field :street, class: "form-control", placeholder: "Voie" %>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col">
          <%= ff.text_field :additionnal_information, class: "form-control", placeholder: "Complément d'adresse"%>
        </div>
      </div>
      <div class="row mb-1">
        <div class="col">
        <%= ff.text_field :zip_code, class: "form-control", placeholder: "Code postal" %>
      </div>
      <div class="col">
        <%= ff.text_field :city, class: "form-control", placeholder: "Ville"%>
      </div>
      </div>
      <%end%>
    </div>
    <div class="mb-3">
      <%= label_tag "Ajoutez une photo à l'évènement"%><br/>
      <%= f.file_field :illustration%>
    </div>
    <div class="mb-3">
      <%= f.submit "Modifier l'évènement", class: 'btn btn-primary btn-lg'  %>
    </div>
    <br/>
  <% end %>
</div>
</div>

app/views/events/index.html.erb
<h1 class="d-flex justify-content-center mt-5 mx-2">Les prochains évènements organisés par <%= @organization.name%> </h1>
  <%= render 'events_list'%>
<br/>
<div class="container py-5">
  <div class="text-center">
    <% if ((current_user.organization.nil? == false && current_user.organization.id == @organization.id) || current_user.admin == true) %>
      <p>
        Vous souhaitez partager le prochain évènement de <%= @organization.name%> ?<br/> Rendez vous ici :
      </p>
      <%= link_to "Créer un nouvel évènement", new_organization_event_path, class: 'btn btn-outline-primary' %>
    <%end%>
  </div>
</div>

app/views/events/new.html.erb
 <section>
    <br/>
    <div class="container bg-white justify-content-center">
    <br/>
      <h1 class="mt-5">Créer un évènement</h1>
      <div class="container d-flex justify-content-center ">
        <div class="col-md-8 order-md-1">
          <%= form_tag organization_events_path(@organization.slug), method: "post", multipart: true do %>
            <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> ><br/>
              <div class="mb-3">
                <%= label_tag "Titre de l'évènement*" %> <br/>
                <%= text_field_tag 'title', "", class: "form-control", placeholder: "Titre"%>
                <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire </div>
              </div>
              <div class="mb-3">
                <%= label_tag "Description de l'évènement*" %> <br/>
                <%= text_area_tag 'description', "", class: "form-control"%>
                <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire</div>
              </div>
              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <%= label_tag "Début de l'évènement*" %> <br/>
                    <%= date_field_tag 'start_date', "", class: "form-control"%>
                    <%= time_field_tag 'start_time', "", class: "form-control"%>
                    <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire</div>
                  </div>
                  <div class="col">
                    <%= label_tag "Fin de l'évènement" %> <br/>
                    <%= date_field_tag 'end_date', "", class: "form-control"%>
                    <%= time_field_tag 'end_time', "", class: "form-control"%>
                    <div class="invalid-feedback" style="width: 100%;"> Ce champs est obligatoire</div>
                  </div>
                </div>
              </div>
              <div class="mb-3">
                  <%= label_tag "Lieu de l'évènement"%>
                  <div class="row mb-1">
                    <div class="col">
                      <%= text_field_tag 'number', "", class: "form-control", placeholder: "N°"  %>
                    </div>
                    <div class="col">
                      <%= text_field_tag 'street', "", class: "form-control", placeholder: "Voie"%>
                    </div>
                  </div>
                  <div class="row mb-1">
                    <div class="col">
                      <%= text_field_tag 'additionnal_information', "", class: "form-control", placeholder: "Complément d'adresse"%>
                    </div>
                  </div>
                  <div class="row mb-1">
                    <div class="col">
                    <%= text_field_tag 'zip_code', "", class: "form-control", placeholder: "Code Postal*"%>
                  </div>
                  <div class="col">
                    <%= text_field_tag 'city', "", class: "form-control", placeholder: "Ville"%>
                  </div>
                  </div>
              </div>
              <div class="mb-3">
                <%= label_tag "Ajoutez une photo à l'évènement"%><br/>
                <%= file_field_tag 'illustration'%>
              </div>
              <div class="mb-3">
                <%= submit_tag "Créer l'évènement", class: 'btn btn-primary btn-lg'  %>
              </div>
              <br/>
          <% end %>
          
        </div>
      </div>
    </div>
</section>

app/views/events/show.html.erb
<div class="container-fluid py-5 bg-orange-gradient">
  <br>
</div>

<div class="container mt-n5">
  <div class="row">
    <div class="col-md-2 text-center">
        <%if @organization.logo.attached?%>
          <%= image_tag @organization.logo, alt: 'logo', class:"rounded-circle", height:"100", width:"100" %>
        <%else%>
          <%= image_tag "mains.jpg", alt:"", class:"rounded-circle", height:"120", width:"120" %>
        <%end%>
    </div>
    <div class="col-md-6 text-center text-md-left">
      <h1> <%= @event.title %> </h1>
      <p>Organisé par: <%=link_to "#{@organization.name}", organization_path(@organization.slug) %></p>
    </div>
    <div class="col-md-4 text-center text-md-right">
      <% if (current_user && ((current_user.organization.nil? == false && current_user.organization.id == @organization.id) || current_user.admin == true)) %>
        <%= link_to "Editer l'évènement", edit_organization_event_path(@organization.slug,@event.slug), class: 'btn btn-primary' %>
      <%end%>
    </div>
  </div>
</div>
<div class="container my-3">
  <div class="d-flex row">
    <div class="col-sm-12 col-md-4">
    <%if @event.illustration.attached?%>
        <%= image_tag @event.illustration, class:"card-img-top"%>
      <%else%>
        <%= image_tag "event.jpg", class:"card-img-top top-image"%>
      <%end%>
    </div>
    <div class="col-sm-12 col-md-4 d-flex flex-column justify-content-between mt-1">
      <h5>À Propos</h5>
      <p><%=@event.description%></p>
      <%if current_user%>
        <% @participation = Participation.find_by(user_id:current_user.id, event_id:@event.id)%>
        <%if @participation == nil%>
          <%= link_to "S'inscrire", organization_event_participations_path(@organization.slug,@event.slug), class: 'btn btn-secondary w-50', method: :post %>
        <%else%>
          <%= link_to "Se désinscrire", organization_event_participation_path(@organization.slug,@event.slug,@participation.id), class: 'btn btn-secondary w-50', method: :delete %>
        <%end%>
      <%else%>
        <%= link_to "S'inscrire", new_user_session_path, class: 'btn btn-secondary w-50'%>
      <%end%>
    </div>
    <div class="col-sm-12 col-md-4 mt-1">
      <h5>Détails de l'évenement</h5>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><p>Lieu : <%=@event.address.number%> <%=@event.address.street%><br/><%=@event.address.zip_code%> <%=@event.address.city%></p></li>
            <li class="list-group-item"><p>Début : le <%=@event.start_date.strftime("%d/%m/20%y à %Hh%M")%></p></li>
            <li class="list-group-item"><p><% unless @event.end_date.nil? %>Fin : <%=@event.end_date.strftime("%d/%m/20%y à %Hh%M")%> <%end%></p></li>
          </ul>
    </div>
  </div>
  <div class="text-muted">
      <% if (current_user && ((current_user.organization.nil? == false && current_user.organization.id == @organization.id) || current_user.admin == true)) %>
        <hr>
        <div class="row">
          <div class="col-md-5 text-center text-md-left">
            [Informations réservées aux admins]<br>
          </div>
          <div class="col-md-7 text-md-right">
            <%= link_to "Envoyer un message à tous les participants", thredded.new_private_topic_path(private_topic: {title: "A propos de l'évènement '#{@event.title}'", user_names: "#{@attendants.join(', ')}"}), class: 'btn btn-primary'%>
          </div>
          <div class="col-md-8 text-center text-md-left">
            Voici les participants à votre évènement :  <br>
            <%= @attendants.join(", ") %>
          </div>
        </div>
      <%end%>
  </div>
</div>
    <!-- ***** Google maps ***** -->
<div class="container-fluid py-3 bg-purple-gradient">
  <div class="container">
      <div class="row text-center">
        <div class="col py-3">
          <h2>
            Plan d'accès :
          </h2>
        </div>
      </div>
      <div class="row d-flex mb-3 justify-content-center">
        <%= link_to image_tag("https://maps.googleapis.com/maps/api/staticmap?markers=color:0x7776BC%7C#{@event.address.google_format},France&zoom=14&size=700x300&key=#{ENV['google_key']}"), "https://www.google.com/maps/search/?api=1&query=#{@event.address.google_format},France", height:"300", width:"700", target:"_blank" %>
      </div>
  </div>
</div>

    <!-- ***** Organization informations ***** -->
<div class="container-fluid py-3 bg-orange-gradient">
  <div class="container">
      <div class="row text-center">
        <div class="col py-3">
          <h2>
            Contacter l'organisateur :
          </h2>
        </div>
      </div>
      <div class="row d-flex justify-content-center">
        <div class="col-md-3">

          <p><i class="fas fa-home"></i>  <%= @organization.address.numberandstreet %> </p>
          <p><i class="fas fa-map-marker-alt"></i>  <%= @organization.address.zip_codeandcity %> </p>
          <p><i class="fas fa-phone-alt"></i>  <%= @organization.phone %> </p>
        </div>
        <div class="col-md-3">
          <% unless @organization.email.nil? %>
            <p><i class="fas fa-envelope"></i> <%=@organization.email%> </p>
          <%end%>
          <% unless @organization.website.nil? %>
            <p><i class="fas fa-globe"></i> <%= link_to @organization.website, @organization.website, target:"_blank"%> </p>
          <%end%>
          <% unless @organization.fb_website.nil? %>
            <p> <i class="fab fa-facebook">  </i> <%= link_to "Notre Facebook", @organization.fb_website, target:"_blank" %> <p>
          <%end%>
        </div>
      </div>
  </div>
</div>
    <!-- ***** Donate Section ***** -->

<div class="container">
  <div class="row py-3">
    <div class="col text-center">
      <h2 class="py-3"> Soutenir l'organisateur : </h2>
      <p> <%= @organization.description %> </p>
      <%= link_to 'Faire un don', @organization.donate_link, class: 'btn btn-primary my-3', target:"_blank" %>
    </div>
  </div>
</div>
    <!-- ***** Other Events from this association ***** -->
  <div class="container-fluid bg-orange-gradient py-5 mt-3">
        <h3 class="text-center pb-2">Autres évènements organisés par <%= @organization.name%> </h3>
            <%= render 'events/events_list'%>
</div>