config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %i[show edit update destroy]
  resource :admin, only: [:show]
  resource :allevents, only: [:show]
  resources :organizations, param: :slug do
    patch :validate # only for the admin of the website
    resources :follows, only: %i[create destroy]
    resources :events, param: :slug do
      resources :participations, only: %i[create destroy]
    end
  end
  resources :articles, param: :slug do
    resources :article_likes, only: %i[create destroy]
    resources :article_comments
  end
  root to: 'home#index'
  get '/static/:page' => 'static#show'
  get "static/team", :as => 'team'
  mount Thredded::Engine => '/forum'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  has_one_attached :logo
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { in: 100..200, wrong_length: '100 to 200 characters is allowed' }
  validates :num_rna, presence: true, format: { with: /\A([W]([0-9]{9}))\z/, message: 'please enter a valid french association num W+9nbs' }
  # validates :email, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  belongs_to :user
  belongs_to :address
  has_one_attached :logo
  has_many :follows, dependent: :destroy
  has_many :users, through: :follows
  has_many :events, dependent: :destroy
  has_many :items
  extend FriendlyId
  friendly_id :name, use: :slugged

  def followers
    users
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  include OrganizationsHelper
  before_action :authenticate_admin, only: %i[destroy validate]
  before_action :authenticate_user_assoc_or_admin, only: %i[edit update]
  before_action :address_validation, only: [:create]
  before_action :authenticate_canbeadmin_or_admin, only: %i[new create]

  def index
    @organizations = Organization.all.where(validatedbyadmin: true).order('created_at desc')
  end

  def show
    @organization = Organization.friendly.find_by_slug(params[:slug])
    @address = Address.find(@organization.address_id)
    @events = @organization.events.sort_by(&:start_date)
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(address_id: @address.id, name: params[:organization][:name], logo: params[:organization][:logo], description: params[:organization][:description], phone: params[:organization][:phone], website: params[:organization][:website], fb_website: params[:organization][:fb_website], email: params[:organization][:email], num_rna: params[:organization][:num_rna], donate_link: params[:organization][:donate_link], content: params[:organization][:content])
    @organization.user_id = current_user.id
    if @organization.save
      flash[:success] = "Merci l'association est en cours de validation par l'administration"
      redirect_to organizations_path
    else
      flash.now[:error] = "Désolé il y a une erreur :#{@organization.errors.full_messages.to_sentence}"
      @address.destroy
      render :new
    end
  end

  def edit
    @organization = Organization.friendly.find_by_slug(params[:slug])
    @address = Address.find(@organization.address_id)
  end

  def validate
    @organization = Organization.friendly.find_by_slug(params[:organization_slug])
    @organization.validatedbyadmin == false ? @organization.update(validatedbyadmin: true) : @organization.update(validatedbyadmin: false)
    flash[:success] = 'Les informations ont bien été prises en compte'
    redirect_back(fallback_location: admin_path)
  end

  def update
    @organization = Organization.friendly.find_by_slug(params[:slug])
    @address = Address.find(@organization.address_id)
    if @organization.update(post_params) && @address.update(address_params)
      flash[:success] = 'Les informations ont bien été prises en compte'
      redirect_to organization_path(@organization.slug)
    else
      flash[:error] = "Désolé il y a une erreur :#{@organization.errors.full_messages.to_sentence} #{@address.errors.full_messages.to_sentence}"
      redirect_to organization_path(@organization.slug)
    end
  end

  def destroy
    @organization = Organization.friendly.find_by_slug(params[:slug])
    @address = Address.find(@organization.address_id)
    @organization.user.articles.destroy_all
    @organization.destroy
    flash[:success] = "L'association a été supprimée'"
    redirect_to organizations_path
  end

  private

  def post_params
    params.require(:organization).permit(:name, :description, :website, :fb_website, :email, :num_rna, :logo, :content, :donate_link, :validatedbyadmin, address_attributes: %i[number street additionnal_information zip_code city])
  end

  def address_params
    params.require(:address).permit(:number, :street, :additionnal_information, :zip_code, :city)
  end
end

app/helpers/organizations_helper.rb
# frozen_string_literal: true

module OrganizationsHelper
  def authenticate_user_assoc_or_admin # the admin of the organiation or admin
    @organization = Organization.friendly.find_by_slug(params[:slug])
    unless (current_user && current_user.organization.nil? == false && current_user.organization.id == @organization.id) || (current_user && current_user.admin == true)
      redirect_to root_path
    end
  end

  def authenticate_canbeadmin_or_admin # only the admin or a current_user who does not have any other orga
    unless current_user && (current_user.organization.nil? == true || current_user.admin == true)
      redirect_to root_path
    end
  end
end

app/views/organizations/_card.html.erb
<div class="col-md-6 mt-4">
    <div class="card h-100">
        <div class="card-body d-flex flex-row">
            <div class="col-md-4 d-flex flex-column justify-content-center">
                <%if organization.logo.attached?%>
                   <%= image_tag organization.logo, alt: 'logo', class:"rounded-circle", height:"100", width:"100" %>
                <%else%>
                    <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSg6Tiu7ix5m4sH3bRK550_NoTJLhA99xzuq9IsxLbtnQEDBGNi", alt:"", class:"rounded-circle", height:"120", width:"120" %>
                <%end%>
                <div class="row pl-3 pt-2" style="font-size: 14px"><%= organization.location %></div>
            </div>
            <div class="col-md-8 d-flex flex-column justify-content-center">
                <h4 class="card-title self-align-top"> <%= organization.name %> </h4>
                <p class="card-text"> <%= organization.description %>
            </div>
            </div>
            <div class="card-footer d-flex justify-content-between">
                <div class="btn btn-primary"> <%= link_to "En savoir plus", organization_path(organization.id), :class => "text-white" %>  </div>
                <%if current_user%>
                  <% @follow = Follow.find_by(user_id:current_user.id, organization_id:organization.id)%>
                  <%if @follow == nil%>
                    <%= link_to "Suivre", organization_follows_path(organization.id), method: :post, :class => "btn btn-secondary"  %>
                  <%else%>
                    <%= link_to "Ne plus suivre", organization_follow_path(organization.id, @follow.id), method: :delete, :class => "btn btn-secondary" %>
                  <%end%>
                <%else%>
                    <%= link_to "Suivre", new_user_session_path, :class => "btn btn-secondary"%>
                <%end%>
            </div>
    </div>
</div> 

app/views/organizations/_orga_form.html.erb
<%= form_for @organization do |f| %>
  <div class="container mt-n5">
    <div class="row">
      <div class="col-md-8 text-center text-md-left">
        <%= label_tag 'Le nom : '%>
        <%= f.text_field :name %> (*) <br/>
        <%= label_tag 'Le numéro du registre RNA : '%>
        <%= f.text_field  :num_rna, placeholder: "W000000000"  %> (*)
      </div>
    </div>
  </div>
  <div class="container bg-light py-3">
    <div class="row">
      <div class="col py-3 text-center">
        <h4 class="pb-3">
          Slogan : <small>(petite description entre 100 et 200 caractères)</small> (*)
        </h4>
        <p> <%= f.text_area :description, class: 'w-75' %> </p>
      </div>
    </div>
    <div class="row">
        <div class="col py-3 text-center">
          <h4 class="pb-3">
            Dites nous en plus : (*)
          </h4>
          <p> <%= f.text_area :content, class: 'w-75', style: 'height: 20rem;' %> </p>
        </div>
    </div>
    <div class="form-group text-center">
      <h4> <%= label_tag "Logo de l'association" %></h4>
        <%= f.file_field :logo %>
    </div>
  </div>
  <div class="container bg-light py-3">
      <h2 class="d-flex justify-content-center">Informations de contacts</h2><br/>
      <div class="container d-flex justify-content-center">
        <div class=" text-center">   
                <%= fields_for @address do |ff| %>
                  <div class="form-group">
                    <%= label_tag "Adresse : "%>
                  </div>
                  <div class="row text-md-left text-center py-3">
                    <div class="col-md-6 pl-5">
                      <%= ff.text_field :number, class: "form-control", placeholder: "N°" %>
                    </div>
                    <div class="col-md-6 pl-5">
                      <%= ff.text_field :street, class: "form-control", placeholder: "Voie" %>
                    </div>
                  </div>
                  <div class="row text-md-left text-center py-3">
                    <div class="col-md-6 pl-5">
                      <%= ff.text_field :additionnal_information, class: "form-control", placeholder: "Complément d'adresse"%>
                    </div>
                  </div>
                  <div class="row text-md-left text-center py-3">
                    <div class="col-md-6 pl-5">
                      <%= ff.text_field :zip_code, class: "form-control", placeholder: "Code postal" %>
                    </div>
                    <div class="col-md-6 pl-5">
                      <%= ff.text_field :city, class: "form-control", placeholder: "Ville"%>
                    </div>
                  </div>
                <%end%>
              <div class="form-group">
                <%= label_tag "Le site internet" %> <br/>
                <%= f.text_field :website%> 
              </div>
              <div class="form-group">
                <%= label_tag "Le lien Facebook" %> <br/>
                <%= f.text_field :fb_website%> 
              </div>
              <div class="form-group">
                <%= label_tag "L'email de contact" %> <br/>
                <%= f.text_field :email%> 
              </div>
              <div class="form-group">
                <%= label_tag "Le numero de téléphone" %> <br/>
                <%= f.text_field :phone%> 
              </div>
              <span class="text-muted" style="font-size: 10px">les champs avec (*) sont obligatoires</span>
        </div>
      </div>
  </div>
  <div class="container bg-light py-3">
    <div class="row py-3">
      <div class="col text-center">
        <h2 class="py-3"> Soutenir l'association : </h2>
          <div class="form-group">
                  <%= label_tag "Lien pour faire des dons" %> <br/>
                  <%= f.text_field :donate_link%> 
          </div>
      </div>
    </div>
    <div class="row text-center py-3">
      <div class="col">
        <%= f.submit 'Valider', class: "btn btn-primary" %>      
      </div>
    </div>
  </div>
<% end %>

app/views/organizations/_orga_show.html.erb
<div class="container mt-n5">
<!-- ***** Main info ***** -->
  <div class="row">
    <div class="col-md-2 text-center">
      <%if @organization.logo.attached?%>
        <%= image_tag @organization.logo, alt: 'logo', class:"rounded-circle", height:"120", width:"120" %>
      <%else%>
        <%= image_tag "mains.jpg", alt:"", class:"rounded-circle", height:"120", width:"120" %>
      <%end%>
    </div>
    <div class="col-md-6 text-center text-md-left">
      <h1> <%= @organization.name %> </h1>
      <p><%= @organization.description %></p>
    </div>
    <div class="col-md-4 text-md-right">
      <% if current_user %>
        <div class="flex row d-flex justify-content-around">
          <% if ((current_user.organization.nil? == false && current_user.organization.id == @organization.id) || current_user.admin == true) %>
            <%= link_to "Editer infos", edit_organization_path(@organization.slug), class: 'btn btn-primary' %>
          <%end%>
          <div id="follow <%= @organization.id%>">
            <%= render 'follows/follow_button', organization: @organization%>
          </div>
        </div>
      <%else%>
        <%= link_to "Suivre", new_user_session_path, class: 'btn btn-secondary'%>
      <%end%>
    </div>
  </div>

<!-- ***** Description content ***** -->
  <div class="row py-3">
    <div class="col py-3">
      <h2 class="pb-3">
        Description :
      </h2>
      <p> <%= @organization.content %> </p>
    </div>
  </div>
</div>

<!-- ***** Next Events ***** -->

<div class="container-fluid bg-orange-gradient py-3 mt-3">
        <h3 class="text-center pb-2">Nos prochains évènements : </h3>
        <%= render 'events/events_list'%>
</div>

<!-- ***** Contact Us ***** -->
<div class="container-fluid py-3 bg-orange-gradient">
  <div class="container">
      <div class="row text-center">
        <div class="col py-3">
          <h2>
            Nous Contacter :
          </h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">

          <p><i class="fas fa-home"></i>  <%= @organization.address.numberandstreet %></p>
          <p><i class="fas fa-map-marker-alt"></i>  <%= @organization.address.zip_codeandcity %></p>
          <p><i class="fas fa-phone-alt"></i>  <%= @organization.phone %> </p>
        </div>
<!-- ***** Contact infos ***** -->
        <div class="col-md-5">
          <% unless @organization.email.nil? %>
            <p><i class="fas fa-envelope"></i> <%= @organization.email%> </p>
          <%end%>
          <% unless @organization.website.nil? %>
            <p><i class="fas fa-globe"></i> <%= link_to @organization.website, @organization.website, target:"_blank"%> </p>
          <%end%>
          <% unless @organization.fb_website.nil? %>
            <p> <i class="fab fa-facebook">  </i> <%= link_to "Notre Facebook", @organization.fb_website, target:"_blank"%> <p>
          <%end%>
          <%if current_user%>
            <p> <i class="fas fa-comment"> </i> <%= link_to "L'administrateur #{@organization.user.name}", thredded.new_private_topic_path(private_topic: {title: "A propos de l'association '#{@organization.name}'", user_names: "#{@organization.user.name}"}) %><p>
          <%end%>
        </div>
      </div>
  </div>
</div>
    <!-- ***** Google maps ***** -->
<div class="container-fluid py-3 bg-purple-gradient">
  <div class="container">
      <div class="row text-center">
        <div class="col py-3">
          <h2>
            Plan d'accès :
          </h2>
        </div>
      </div>
      <div class="row d-flex mb-3 justify-content-center">
        <%= link_to image_tag("https://maps.googleapis.com/maps/api/staticmap?markers=color:0x7776BC%7C#{@organization.address.google_format},France&zoom=14&size=700x300&key=#{ENV['google_key']}"), "https://www.google.com/maps/search/?api=1&query=#{@organization.address.google_format},France", height:"300", width:"700", target:"_blank" %>
      </div>
  </div>
</div>
<!-- ***** Donnation section ***** -->
<div class="container">
  <div class="row py-3">
    <div class="col text-center">
      <h2 class="py-3"> Nous soutenir : </h2>
      <p class="text-md-left"><%= @organization.description %> </p>
      <%= link_to 'Faire un don', @organization.donate_link, class: 'btn btn-primary my-3', target:"_blank" %>
    </div>
  </div>
</div>

app/views/organizations/_organization_card.html.erb
<div class="col-md-3 m-4">
<!-- ***** Popover information && Template***** -->
  <div class="row shadow p-3 usertype-cardmodel" data-container="body" data-toggle="popover" data-placement="top" data-content="<%= organization.description%>" data-template='<div class="popover" role="tooltip"><div class="arrow"></div><p class="popover-body"></p></div>'>

    <!-- ***** Logo ***** -->
    <div class="col-md-4 text-center my-auto">
      <%if organization.logo.attached?%>
         <%= image_tag organization.logo, alt: "logo", class:"rounded-circle", height:"100", width:"100" %>
      <%else%>
          <%= image_tag "mains.jpg", alt:"", class:"rounded-circle", height:"120", width:"120" %>
      <%end%>
    </div>
    <div class="col-md-12">
      <!-- ***** Name ***** -->
      <h4 class="text-md-left text-center">
        <% if organization.name.chars.count > 15 %>
          <%= organization.name[0..14] + "..." %>
        <% else %>
          <%= organization.name %>
        <% end %>
      </h4>
      <!-- ***** Location ***** -->
      <p class="my-4">
        <i class="fas fa-map-marker-alt"></i> <%= organization.address.city %>
      </p>
      <!-- ***** Follow and see more buttons ***** -->
      <div class="row text-md-left text-center">
        <div class="col-6">
          <%if current_user %>
            <div id="follow <%= organization.id%>">
              <%= render 'follows/follow_button', organization: organization%>
            </div>
          <%else%>
            <%= link_to "Suivre", new_user_session_path, :class => "btn btn-outline-secondary"%>
          <%end%>
        </div>
        <div class="col-6">
          <%= link_to "Découvrir", organization_path(organization.slug), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organizations/edit.html.erb
<div class="container-fluid py-5 bg-orange-gradient">
  <br>
</div>

<div class="container mt-n5">
  <div class="row">
    <div class="col-md-2 text-center">
      <%if @organization.logo.attached?%>
        <%= image_tag @organization.logo, alt: 'logo', class:"rounded-circle", height:"120", width:"120" %>
      <%else%>
        <%= image_tag "mains.jpg", alt:"", class:"rounded-circle", height:"120", width:"120" %>
      <%end%>
    </div>
    <div class="col-md-10 text-center text-md-left">
      <h1> <%= @organization.name %> </h1>
      <h1>Modifier les informations</h1>
    </div>
  </div>
</div>

<div class="container mt-5">
  <%= render 'organizations/orga_form' %>
</div>

<div class="row py-3">
  <div class="col text-center">
    <% if current_user && current_user.admin == true %>
      <p>Pour supprimer le compte de cette association ainsi que ses informations, cliquer ici : </p>
      <%= link_to "Supprimer",organization_path(@organization.slug), method: :delete, data: {confirm: "Etes vous surs? L'association sera définitevement supprimée"}, class: 'btn btn-outline-primary' %>
    <%end%>
  </div>
</div>

app/views/organizations/index.html.erb
<!-- ***** HEADER ***** -->
<div class="container-fluid bg-orange-gradient">
  <div class="container py-3">
    <div class="row py-5">
      <div class="col-md-9 mt-5">
        <h1>Nos associations partenaires : </h1>
        <p class="py-3">Vous trouverez dans cette rubrique la liste de nos associations partenaires. Avant de nous rejoindre, chaque association fait l'objet d'une vérification détaillée, afin de vous garantir leur professionnalisme et l'identité de ses membres.</p>
      </div>
    </div>
  </div>
</div>

<!-- ***** Add my organizations section ***** -->
<div class="container pt-5">
  <div class="row text-center justify-content-center">
    <% if current_user && current_user.organization.nil? %>
          <p>
            Vous gèrez une association et vous aimeriez qu'elle apparaisse sur notre site, partager ses évènements, son actualité, etc. ?<br> Rendez vous ici :
          </p>
          <%= link_to "Espace association", new_organization_path(), :class => "btn btn-outline-primary" %>
    <%end%>
  </div>
</div>

<!-- ***** Organizations list ***** -->
<div class="container-fluid py-5">
  <div class="row justify-content-center">
    <% @organizations.each do |organization| %>
      <%= link_to (render 'organization_card', organization: organization), organization_path(organization.slug) %>
    <% end %>
  </div>
</div>

<!-- ***** Display description in Popover on hover ***** -->
<script type="text/javascript">
  $(function () {
    $('[data-toggle="popover"]').popover({ trigger: "hover" })
  })
</script>

app/views/organizations/new.html.erb
<div class="container-fluid py-5 bg-orange-gradient">
  <br>
</div>

<div class="container mt-n5 pb-3">
  <div class="row ">
    <div class="col-md-10 text-center text-md-left">
      <h1>Inscrire une association</h1>
    </div>
  </div>
</div>

<div class="container mt-5">
    <%= render 'organizations/orga_form' %>
</div>

app/views/organizations/show.html.erb
<% if current_user && current_user.organization.nil? == false && current_user.organization.id == @organization.id %>
  <div class="container-fluid py-5 bg-orange-gradient">
    <div class="row">
      <div class="col-md-7 text-md-right">
        <h1 class=""> Votre Dashboard </h1>
      </div>
      <div id="buttondashboard" class="col-md-5 text-md-left d-none">
        <%= link_to "Revenir sur le Dashboard", organization_path(@organization.slug), class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>

  <div id="showorganization" class="container mt-5">
    <div class="text-right">
      <%= link_to "Voir la vue utilisateur", organization_path(@organization.slug), remote:true, class: 'btn btn-secondary' %>
    </div>
    <%= render 'organizations/orga_form' %>
  </div>

  <div class="container mt-5">
    <hr>
    <div class="row">
      <div class="col-md-8 text-center text-md-left">
        <h1 class=""> Les évènements de l'association </h1>
      </div>
      <div class="col-md-4 text-center text-md-right">
        <%= link_to "Créer un évènement", new_organization_event_path(@organization.slug), class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="pb-5">
      <%= render 'events/events_list' %>
    </div>
  </div>

<%else%>

  <div class="container-fluid py-5 bg-orange-gradient">
    <br>
  </div>
  <%= render 'organizations/orga_show' %>

<%end%>

app/views/organizations/show.js.erb
//alert("le fichier JS est exécuté!");
document.getElementById("showorganization").innerHTML = 
	"<%= j render 'orga_show', organization: @organization %>" + "<hr>" +
	"<h4 class='text-center'> La partie ci dessous n'est pas visible aux utilisateurs</h4>";
document.getElementById("buttondashboard").classList.remove("d-none");